# Generated by Django 5.1.6 on 2025-03-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('cloth', 'Clothing'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=20),
        ),
    ]
