# Generated by Django 5.1.6 on 2025-03-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_tracker', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
